"use client";
import { useState } from "react";

const menu = ["Dashboard", "Clientes", "Auditorias", "Formulários", "Não conformidades", "Planos de ação", "Visitas", "Documentos", "Relatórios", "Configurações"];
const cards = [{label:"Clientes ativos", value:"0", tone:"blue"}, {label:"Auditorias em andamento", value:"0", tone:"purple"}, {label:"NCs abertas", value:"0", tone:"orange"}, {label:"Conformidade geral", value:"—", tone:"green"}];

export default function Home() {
  const [active, setActive] = useState("Dashboard");
  return <main className="shell"><aside><div className="brand"><span className="brand-mark">E</span><span>Épico<span className="muted">.check</span></span></div><div className="workspace"><span className="org-dot"/> Minha consultoria <span className="chevron">⌄</span></div><nav>{menu.map((item, i) => <button key={item} className={active===item?"nav-item active":"nav-item"} onClick={()=>setActive(item)}><span className="nav-icon">{["⌂","▣","◫","☷","!","↗","◷","▤","▥","⚙"][i]}</span>{item}</button>)}</nav><div className="side-footer"><div className="help">?</div><div><strong>Precisa de ajuda?</strong><small>Fale com o suporte</small></div></div></aside><section className="content"><header><div><div className="crumb">Início <span>/</span> {active}</div><h1>{active}</h1></div><div className="header-actions"><button className="icon-btn">⌕</button><button className="icon-btn">♧</button><div className="avatar">AC</div><div className="user"><strong>Administrador</strong><small>admin@consultoria.com</small></div></div></header>{active === "Dashboard" ? <Dashboard cards={cards}/> : <Empty title={active}/>}</section></main>
}
function Dashboard({cards}:{cards:{label:string,value:string,tone:string}[]}) { return <><div className="welcome"><div><h2>Bom dia, administrador <span>✦</span></h2><p>Acompanhe o desempenho da sua consultoria.</p></div><button className="primary">＋ Nova auditoria</button></div><div className="cards">{cards.map(c=><div className="card" key={c.label}><div className={`card-icon ${c.tone}`}>◈</div><div><span>{c.label}</span><strong>{c.value}</strong><small>Sem dados registrados ainda</small></div></div>)}</div><div className="grid"><div className="panel chart"><div className="panel-head"><div><h3>Evolução da conformidade</h3><p>Índice médio nos últimos 6 meses</p></div><button className="select">Últimos 6 meses⌄</button></div><div className="empty-chart"><div className="chart-line">Nenhuma auditoria concluída</div><span>Cadastre sua primeira auditoria para acompanhar a evolução.</span></div></div><div className="panel"><div className="panel-head"><div><h3>Próximas auditorias</h3><p>Agenda da consultoria</p></div><button className="link">Ver todas →</button></div><div className="empty"><div className="empty-icon">◷</div><strong>Nenhuma auditoria agendada</strong><span>As próximas auditorias aparecerão aqui.</span></div></div></div></> }
function Empty({title}:{title:string}) { return <div className="panel page-empty"><div className="empty-icon">✦</div><h2>{title}</h2><p>Este módulo será conectado aos dados reais do Supabase na próxima etapa.</p><button className="primary">＋ Criar primeiro registro</button></div> }

